name: TownIndex
main: src.townindex.TI_Main
author: [KipperOrigin, GoalieGuy6]
version: 0.4

commands:
  ti:
    description: This is Town Index's main command.
    usage: /ti <add|remove>
    aliases: [town, townindex]

permissions:
  ti.basic.*:
    description: Town Index Basics.
    default: op
    children:
      ti.basic.help: true
      ti.basic.list: true
      ti.basic.info: true
      ti.basic.edit.*: true
  ti.basic.help:
    description: Town Index Help.
    default: op
  ti.basic.list:
    description: Town Index list.
    default: op
  ti.basic.info:
    description: Town Index info.
    default: op
  ti.basic.edit.*:
    description: All Town Index edit permissions.
    default: op
    children:
      ti.basic.edit.vmayor: true
      ti.basic.edit.location: true
      ti.basic.edit.plots: true
      ti.basic.edit.wing: true
      ti.basic.edit.motd: true
  ti.basic.edit.vmayor:
    description: Edits a towns vice mayor.
    default: op
  ti.basic.edit.location:
    description: Edits a towns location.
    default: op
  ti.basic.edit.plots:
    description: Edits a towns plots status.
    default: op
  ti.basic.edit.wing:
    description: Edits a towns wing location.
    default: op
  ti.basic.edit.motd:
    description: Edits town Motd.
    default: op
  ti.admin.*:
    description: All Town Index Admin permissions.
    default: op
    children:
      ti.admin.edit: true
      ti.admin.add: true
      ti.admin.remove: true
      ti.admin.help: true
  ti.admin.edit:
    description: Editing bypass, and access to more editing.
    default: op
  ti.admin.add:
    description: Adds a town.
    default: op
  ti.admin.remove:
    description: Removes a town.
    default: op
  ti.admin.help:
    description: Admin help.
    default: op